DROP TYPE DIRECCION FORCE;
DROP TYPE PERSONA FORCE;
DROP TYPE T_ALUMNO FORCE;
DROP TYPE T_MOVIM FORCE;
DROP TYPE TELEFONO FORCE;
DROP TYPE PERSONA_ARRAY FORCE;
DROP TABLE MOVIMIENTOS FORCE;
DROP TABLE ALUMNOS2 FORCE;
DROP TABLE CUENTAS FORCE;
DROP TABLE AGENDA FORCE;
DROP TABLE GRUPOS FORCE;


CREATE OR REPLACE TYPE DIRECCION AS OBJECT(
    CALLE VARCHAR2(20),
    CIUDAD VARCHAR2(25),
    CODIGO_POST NUMBER(5,0)
);
/
CREATE OR REPLACE TYPE PERSONA AS OBJECT(
    CODIGO NUMBER,
    NOMBRE VARCHAR2(35),
    DIREC DIRECCION,
    FECHA_NAC DATE,
    MAP MEMBER FUNCTION POR_CODIGO RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY PERSONA AS
    --
    MAP MEMBER FUNCTION POR_CODIGO RETURN NUMBER IS
        BEGIN
            RETURN SELF.CODIGO;
        END POR_CODIGO;
END;
/
CREATE OR REPLACE TYPE T_ALUMNO AS OBJECT(
    PERS PERSONA,
    N1 NUMBER,
    N2 NUMBER,
    N3 NUMBER,
    MEMBER FUNCTION NOTA_MAS_ALTA RETURN NUMBER,
    MEMBER FUNCTION NOTA_MEDIA RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY T_ALUMNO AS
    --
    MEMBER FUNCTION NOTA_MAS_ALTA RETURN NUMBER IS
    BEGIN
        RETURN GREATEST(SELF.N1, SELF.N2, SELF.N3);
    END;
    --
    MEMBER FUNCTION NOTA_MEDIA RETURN NUMBER IS
    BEGIN
        RETURN (SELF.N1 + SELF.N2 + SELF.N3) / 3;
    END;
END;
/
DECLARE
    DIR DIRECCION;
    PERS PERSONA;
    ALU T_ALUMNO;
BEGIN
    DIR := DIRECCION('Calle Alta', 'Sevilla', 41003);
    PERS := PERSONA(1, 'José Antonio', DIR, '11-12-1995');
    ALU := T_ALUMNO(PERS, 9, 5, 10);

    DBMS_OUTPUT.PUT_LINE('Nota más alta: '|| ALU.NOTA_MAS_ALTA);
    DBMS_OUTPUT.PUT_LINE('Nota media: '|| ALU.NOTA_MEDIA);
END;
/
CREATE TABLE ALUMNOS2 OF T_ALUMNO;
/
DECLARE
    D1 DIRECCION;
    D2 DIRECCION;
    P1 PERSONA;
    P2 PERSONA;
BEGIN
    D1 := DIRECCION('Calle Manolo', 'Sevilla',41002);
    D2 := DIRECCION('Calle Astro', 'Sevilla',41012);
    P1 := PERSONA(2, 'Manolo', D1, '12-12-1967');
    P2 := PERSONA(3, 'Pepa', D2, '12-11-1967');

    IF P1 = P2 THEN
      DBMS_OUTPUT.PUT_LINE('Iguales');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Diferentes');
    END IF;   
END;
/
CREATE TABLE CUENTAS ( 
NUMCTA NUMBER(5) primary key, 
DATOS PERSONA, 
SALDO NUMBER(7,2) 
); 
/
CREATE OR REPLACE TYPE T_MOVIM AS OBJECT ( 
IMPORTE NUMBER(7,2), 
TIPOMOV CHAR, -- I ingreso, R reintegro 
FECHA DATE 
); 
/ 
CREATE TABLE MOVIMIENTOS ( 
NUMCTA NUMBER(5) REFERENCES CUENTAS, 
MOV T_MOVIM, 
CONSTRAINT PK_MOV PRIMARY KEY(NUMCTA, MOV.FECHA) 
); 
/
CREATE OR REPLACE TYPE TELEFONO AS VARRAY(3) OF VARCHAR(9);
/
CREATE TABLE AGENDA(
    NOMBRE VARCHAR2(15),
    TEL TELEFONO
);
/
CREATE OR REPLACE TYPE PERSONA_ARRAY AS VARRAY(5) OF PERSONA;
/
CREATE TABLE GRUPOS(
    NOMBRE VARCHAR2(15),
    PERS PERSONA_ARRAY
);
/