DROP TYPE DIRECCION FORCE;
DROP TYPE PERSONA FORCE;
DROP TYPE T_ALUMNO FORCE;
DROP TYPE T_MOVIM FORCE;
DROP TYPE T_PERSONA FORCE;
DROP TABLE ALUMNOS2 FORCE;
DROP TABLE MOVIMIENTOS FORCE;
DROP TABLE CUENTAS FORCE;
DROP TABLE GRUPOS2 FORCE;

CREATE OR REPLACE TYPE DIRECCION AS OBJECT
(
CALLE VARCHAR2(25),
CIUDAD VARCHAR2(20),
CODIGO_POST NUMBER(5)
);
/
CREATE OR REPLACE TYPE PERSONA AS OBJECT
(
CODIGO NUMBER,
NOMBRE VARCHAR2(35),
DIREC DIRECCION,
FECHA_NAC DATE
);
/
CREATE OR REPLACE TYPE T_ALUMNO AS OBJECT(
    PERS PERSONA,
    N1 NUMBER,
    N2 NUMBER,
    N3 NUMBER,
    MEMBER FUNCTION NOTA_MAS_ALTA RETURN NUMBER,
    MEMBER FUNCTION NOTA_MEDIA RETURN NUMBER 
);
/
CREATE OR REPLACE TYPE BODY T_ALUMNO AS
    --
    MEMBER FUNCTION NOTA_MAS_ALTA RETURN NUMBER IS
    BEGIN
        RETURN GREATEST(SELF.N1, SELF.N2, SELF.N3);
    END;
    --
    MEMBER FUNCTION NOTA_MEDIA RETURN NUMBER IS
    BEGIN
        RETURN (SELF.N1 + SELF.N2 + SELF.N3) / 3;
    END;
END;
/
DECLARE
    DIR DIRECCION;
    PERS PERSONA;
    ALU T_ALUMNO;
BEGIN
    DIR := DIRECCION('Calle Alta', 'Sevilla', 41005);
    PERS := PERSONA(1, 'Fernando Vera', DIR, '02/11/1999');
    ALU := T_ALUMNO(PERS, 10, 9, 6);

    DBMS_OUTPUT.PUT_LINE('Nota más alta: ' || ALU.NOTA_MAS_ALTA);
    DBMS_OUTPUT.PUT_LINE('Nota media: '||ALU.NOTA_MEDIA);
END;
/
CREATE TABLE ALUMNOS2 OF T_ALUMNO;
/
CREATE TABLE CUENTAS (
NUMCTA NUMBER(5) primary key,
DATOS PERSONA,
SALDO NUMBER(7,2)
);

CREATE OR REPLACE TYPE T_MOVIM AS OBJECT (
IMPORTE NUMBER(7,2),
TIPOMOV CHAR, -- I ingreso, R reintegro
FECHA DATE
);
/
CREATE TABLE MOVIMIENTOS (
NUMCTA NUMBER(5) REFERENCES CUENTAS,
MOV T_MOVIM,
CONSTRAINT PK_MOV PRIMARY KEY(NUMCTA, MOV.FECHA)
);
/
CREATE OR REPLACE TYPE T_PERSONAS AS TABLE OF PERSONA;
/
CREATE TABLE GRUPOS2(
    ID NUMBER,
    NOMBRE VARCHAR2(25),
    PERSONAS T_PERSONAS,
    FECHA_CREACION DATE
) NESTED TABLE PERSONAS STORE AS TABLA_PERSONAS;
/
